name: dart_testing
publish_to: none
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.11
